=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.6/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="cd">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="canciones">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cancion" type="T_cancion" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="fecha"/>
      </xs:sequence>
      <xs:attribute name="titulo" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  
  <!--
  <xs:element name="canciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cancion" type="T_cancion" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  -->
  <xs:element name="fecha">
    <xs:complexType>
      <xs:attribute name="dia" type="T_dia" use="required"/>
      <xs:attribute name="mes" type="T_mes" use="required"/>
      <xs:attribute name="anio" type="xs:gYear" use="required"/>      
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="T_dia">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="31"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="T_mes">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="12"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="cancion" type="T_cancion" />
    
  <xs:complexType name="T_cancion">
    
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element ref="compositores"/>
        <xs:element ref="productores"/>
        <xs:element name="sello" type="xs:string"/>
        <xs:element name="artista" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="anio" type="xs:gYear" use="required"/>
      <xs:attribute name="duracion" type="xs:time" use="required"/>
    </xs:complexType>
  
  <xs:element name="compositores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="compositor" type="T_persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="productores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="productor" type="T_persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="T_persona">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="apellidos" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.6/doc.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="esquema.xsd"
    titulo="Titulo del album">
  <canciones>
    <cancion duracion="00:04:47" anio="2008">
      <titulo>Give it 2</titulo>
      <compositores>
        <compositor>
          <nombre>Pharrel</nombre>
          <apellidos>Williams</apellidos>
        </compositor>
      </compositores>
      <productores>
        <productor>
          <nombre>Pharrel</nombre>
          <apellidos>Williams</apellidos>
        </productor>
      </productores>
      <sello>Warner Bros. Records</sello>
      <artista>Madonna</artista>
    </cancion>
  </canciones>
  <fecha dia="20" mes="2" anio="2008"/>
</cd>
