=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 5 DTD/Ejemplo ENTITY No analizadas/libro.dtd
<!NOTATION jpg SYSTEM "c:\programas\visor.exe">
<!ENTITY foto_alhambra SYSTEM "alhambra.jpg" NDATA jpg>
<!ENTITY foto_generalife SYSTEM "generalife.jpg" NDATA jpg>
<!ENTITY foto_torrelavela SYSTEM "torre_de_la_vela.jpg" NDATA jpg>


<!ELEMENT libro (capitulo+)>
<!ATTLIST libro portada ENTITY #REQUIRED>
<!ATTLIST libro fecha NMTOKEN #REQUIRED>

<!ELEMENT capitulo (parrafo,enlace?)+>
<!ATTLIST capitulo  referencia ID #REQUIRED>

<!ELEMENT parrafo (#PCDATA)>

<!ELEMENT enlace EMPTY>
<!ATTLIST enlace destino IDREFS #REQUIRED>

=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 5 DTD/Ejemplo ENTITY No analizadas/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "libro.dtd">
<libro portada="foto_alhambra" fecha="01-01-2013">
   <capitulo referencia="c1">
     <parrafo>sgffg f  d f jdf sdfjk d fdjfdf</parrafo>
     <parrafo>iwtw twrti rtirt rti rtrt rtewois fasdkfsd fs</parrafo>
  </capitulo>
  <capitulo referencia="c2">
     <parrafo>sgffg f  d f jdf sdfjk d fdjfdf</parrafo>
     <enlace destino="c3 c1 c2" />
     <parrafo>iwtw twrti rtirt rti rtrt rtewois fasdkfsd fs</parrafo>
  </capitulo>
  <capitulo referencia="c3">
     <parrafo>sgffg f  d f jdf sdfjk d fdjfdf</parrafo>
     <parrafo>iwtw twrti rtirt rti rtrt rtewois fasdkfsd fs</parrafo>
     <enlace destino="c1" />
  </capitulo>
  <capitulo referencia="c4">
     <parrafo>sgffg f  d f jdf sdfjk d fdjfdf</parrafo>
     <enlace destino="c3 c1" />
     <parrafo>iwtw twrti rtirt rti rtrt rtewois fasdkfsd fs</parrafo>
     <enlace destino="c3 c1" />
  </capitulo>
</libro>
