=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.8/ejercicio5.8.dtd
<!ELEMENT biblioteca (prestamo)>

<!ELEMENT prestamo (bibliotecario, fechas, lector,ejemplares*)>
<!ATTLIST prestamo
          id ID #REQUIRED>
          
<!ELEMENT bibliotecario (#PCDATA)>
<!ATTLIST bibliotecario
          apellidos CDATA #REQUIRED
          nombre CDATA #REQUIRED>
          
<!ELEMENT fechas (#PCDATA)>
<!ATTLIST fechas
          devolucion CDATA #REQUIRED
          prestamo CDATA #REQUIRED>
          
<!ELEMENT lector (id, nombre, telefono+, direccion)>
<!ELEMENT id (#PCDATA)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>

<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion
          cp CDATA #REQUIRED
          letra CDATA #IMPLIED
          localidad CDATA #REQUIRED
          nombrevia CDATA #REQUIRED
          numero CDATA #REQUIRED
          piso CDATA #REQUIRED
          provincia CDATA #REQUIRED
          tipo (calle | avenida) #REQUIRED>
          
<!ELEMENT ejemplares (ejemplar)>
<!ELEMENT ejemplar (autor+)>
<!ATTLIST ejemplar
          registro CDATA #REQUIRED
          titulo CDATA #REQUIRED>
<!ELEMENT autor (#PCDATA)>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.8/ejercicio5.8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio5.8.dtd">
<biblioteca>
  <prestamo id="P001">
    <bibliotecario apellidos="Fernandez" nombre="Anto"/>
    <fechas prestamo="" devolucion=""/>
    <lector>
      <id>l1234</id>
      <nombre>Perico</nombre>
      <telefono>644199321</telefono>
      <telefono>958934872</telefono>
      <direccion tipo="calle" nombrevia="Balsas" numero="4" piso="3" letra="" cp="18650" localidad="Dúrcal" provincia="Granada"/>
    </lector>
    <ejemplares>
      <ejemplar registro="e02" titulo="Juego de Molinos">
        <autor>Cervantes</autor>
        <autor>George RR Martin</autor>
      </ejemplar>
    </ejemplares>
  </prestamo>
</biblioteca>
