=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.12/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="listinPersonas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="email" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="relacion" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
      <xs:attribute name="sexo" type="T_sexo" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="relacion">
    <xs:complexType >
      <xs:attribute name="amigo-de" type="xs:IDREFS"/>
      <xs:attribute name="enemigo-de" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="T_sexo">
    <xs:restriction base="xs:string">
      <xs:pattern value="hombre|mujer"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.12/listinPersonas.xml
<?xml version="1.0" encoding="UTF-8"?>
<listinPersonas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persona.xsd">
	
	<persona id="p1" sexo="hombre">
		<nombre>Batman</nombre>
		<email>mursielagorl@negro.com</email>
		<relacion amigo-de="p3" enemigo-de="p2"/>
	</persona>

	<persona id="p2" sexo="hombre">
		<nombre>Joker</nombre>
		<email>elexcluidodel@baraja.com</email>
		<relacion enemigo-de="p1"/>
	</persona>

	<persona id="p3" sexo="hombre">
		<nombre>Robin</nombre>
		<email>elpekerobin@gmail.com</email>
		<relacion amigo-de="p1" enemigo-de="p2"/>
	</persona>

</listinPersonas>
