=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.11/peliculas.dtd
<!ENTITY OM "obra maestra">
<!ENTITY RE "recomendable">
<!ENTITY PR "prescindible">
<!ENTITY BO "bodrio">

<!ENTITY av SYSTEM "importante.txt">

<!ELEMENT lista_peliculas (aviso, pelicula*)>
<!ELEMENT aviso (#PCDATA)>
<!ELEMENT pelicula (titulo, director+,recomendacion)>
  <!ATTLIST pelicula identificador ID #REQUIRED 
          clasificacion (A | B | C | D | E) "C">
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (nombre, inicial?, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT inicial (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.11/lista_peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_peliculas SYSTEM "peliculas.dtd">
<lista_peliculas>
  <aviso>&av;</aviso>
  <pelicula identificador="p1" clasificacion="A">
    <titulo>Pelicula primera</titulo>
    <director>
      <nombre>Pepe</nombre>
      <inicial>J</inicial>
      <apellido>Santos</apellido>
    </director>
    <recomendacion>&OM;</recomendacion>
  </pelicula>
  <pelicula identificador="p2">
    <titulo>Pelicula segunDA</titulo>
    <director>
      <nombre>Rafael</nombre>
      <apellido>Verdasco</apellido>
    </director>
    <director>
      <nombre>Luisa</nombre>
      <inicial>M</inicial>
      <apellido>Mingorance</apellido>
    </director>
    <recomendacion>&BO;</recomendacion>
  </pelicula>
</lista_peliculas>
