=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 6 XSD/Referencias 3 con atributos/Ferreteria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ferreteria">
		<xs:complexType>
			<xs:sequence>
			  <xs:element ref="articulo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="articulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="descripcion" />
				<xs:element ref="unidades" />
				<xs:element ref="fecha" />
			</xs:sequence>
			<xs:attribute name="cod" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="descripcion" type="xs:string"/>
	<xs:element name="unidades" type="xs:nonNegativeInteger"/>
	<xs:element name="fecha" type="xs:date"/>

</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 6 XSD/Referencias 3 con atributos/Ferreteria.xml
<?xml version="1.0" encoding="utf-8"?>
<ferreteria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:noNamespaceSchemaLocation="ferreteria.xsd">
	<articulo cod="t5">
		<descripcion>Tornillo</descripcion>
		<unidades>50</unidades>
		<fecha>2012-02-14</fecha>
	</articulo>
	<articulo cod="a4">
		<descripcion>Arandelas</descripcion>
		<unidades>5098</unidades>
		<fecha>2012-02-13</fecha>
	</articulo>
</ferreteria>
