=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 6 XSD/Tipos (anonimos y con nombre)/almacen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Tipos complejos anonimos -->
	
	<xs:element name="almacen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="articulo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="articulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="descripcion" type="xs:string"/>
				<xs:element ref="proveedor"/>
				<xs:element name="stock" type="xs:nonNegativeInteger"/>
			</xs:sequence>		
		</xs:complexType>
	</xs:element>
	
	<xs:element name="proveedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="codigo-proveedor" type="xs:string"/>
				<xs:element name="nombre-proveedor" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	

	
	<!-- Tipos complejos con nombre -->	
<!--	
	<xs:element name="almacen" type= "T_Almacen" />

	<xs:complexType name="T_Almacen">
		<xs:sequence>
			<xs:element name="articulo" type="T_Articulo" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="T_Articulo">
		<xs:sequence>
			<xs:element name="descripcion" type="xs:string"/>
			<xs:element name="proveedor" type="T_Proveedor"/>
			<xs:element name="stock" type="xs:nonNegativeInteger"/>
		</xs:sequence>		
	</xs:complexType>

	
	<xs:complexType name="T_Proveedor">
		<xs:sequence>
			<xs:element name="codigo-proveedor" type="xs:string"/>
			<xs:element name="nombre-proveedor" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

-->
	
</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Ejemplos Temas/TEMA 6 XSD/Tipos (anonimos y con nombre)/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<almacen  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		  xsi:noNamespaceSchemaLocation="almacen.xsd">
	<articulo>
		<descripcion>ali-kates</descripcion>
		<proveedor>
			<codigo-proveedor>PR-342</codigo-proveedor>
			<nombre-proveedor>Alfonso</nombre-proveedor>
		</proveedor>
		<stock>345</stock>
	</articulo>
	<articulo>
		<descripcion>martillo pilon</descripcion>
		<proveedor>
			<codigo-proveedor>PR-999</codigo-proveedor>
			<nombre-proveedor>Mauricio</nombre-proveedor>
		</proveedor>
		<stock>12</stock>
	</articulo>
</almacen>
