=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.9/foro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FAQ">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="INFO"/>
        <xs:element maxOccurs="unbounded" ref="PART"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="INFO">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TITULO" type="xs:string"/>
        <xs:element name="AUTOR" type="xs:string"/>
        <xs:element name="EMAIL" type="xs:string"/>
        <xs:element name="VERSION" type="xs:string"/>
        <xs:element name="FECHA" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PART">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Q"/>
      </xs:sequence>
      <xs:attribute name="NO" type="T_parte" use="required"/>
      <xs:attribute name="TITLE" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="T_parte">
    <xs:restriction base="xs:string">
      <xs:pattern value="P[0-9]{1,3}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Q">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="QTEXT" type="xs:string"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="A" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="N" type="T_numero" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="T_numero">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.9/foro.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<FAQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="foro.xsd">
	<INFO>
		<TITULO>WINDOWS98? SOLO SI ME OBLIGAN!</TITULO>
		<AUTOR>Fernando Lorenzo García</AUTOR>
		<EMAIL>Fer@yahoo.es</EMAIL>
		<VERSION>1.0</VERSION>
		<FECHA>1999-05-20</FECHA>
	</INFO>
	<PART NO="P1" TITLE="W95">
		<Q N="1">
			<QTEXT>¿Por qué tengo que instalar W95?</QTEXT>
			<A>A mí también me parece una buena pregunta.</A>
			<A>Y a mí ...</A>
		</Q>
		<Q N="2">
			<QTEXT>¿Y de que me vale?</QTEXT>
			<A>Otra ingeniosa pregunta.</A>
		</Q>
	</PART>
	<PART NO="P2" TITLE="DOS">
		<Q N="1">
			<QTEXT>¿Puedo mantener DOS y W95?</QTEXT>
			<A>Pues si.</A>
		</Q>
		<Q N="2">
			<QTEXT>¿Tengo que cambiar de ordenador?</QTEXT>
			<A>Depende....</A>
		</Q>
		<Q N="3">
			<QTEXT>¿De qué depende?</QTEXT>
		</Q>
	</PART>
</FAQ>
