=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.5/libro.dtd
<!ELEMENT libro (titulo, contenido, copyright)>
<!ELEMENT titulo (#PCDATA)>
<!--<!ELEMENT contenido ((capitulo, separacion)|capitulo)+>-->
<!ELEMENT contenido (capitulo,separacion?)+>
<!ELEMENT capitulo (tema, seccion+)>
<!ATTLIST capitulo
    materia (XML|Java) "XML">
<!ELEMENT tema (#PCDATA)>
<!ELEMENT seccion (#PCDATA)>
<!ATTLIST seccion
    apartados CDATA #REQUIRED
    dificil (no | si) "no">
<!ELEMENT separacion EMPTY>
<!ELEMENT copyright (#PCDATA)>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 5/Ejercicio 5.5/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "libro.dtd">
<libro>
	<titulo>Java y XML</titulo>
	<contenido>
		<capitulo materia="XML">
			<tema>Introduccin</tema>
			<seccion apartados="7">Qué es</seccion>
			<seccion apartados="3">Cómo se usa</seccion>
		</capitulo>
		<capitulo materia="XML">
			<tema>Creando XML</tema>
			<seccion apartados="0">Un documento XML</seccion>
			<seccion apartados="2">La cabecera</seccion>
			<seccion apartados="6">El contenido</seccion>
		</capitulo>
		<capitulo>
		<tema>Analizando XML</tema>
			<seccion apartados="3">Preparación</seccion>
			<seccion apartados="3" dificil="si">SAX</seccion>
			<seccion apartados="9" dificil="si">Manejadores</seccion>
			<seccion apartados="0">Una forma mejor de cargar el analizador</seccion>
		</capitulo>
		<separacion/>
		<capitulo materia="Java">
			<tema>JDOM</tema>
			<seccion apartados="2">Introducción</seccion>
			<seccion apartados="4" dificil="si">DOM&amp;JDOM</seccion>
		</capitulo>
	</contenido>
	<copyright>2000</copyright>
</libro>
