=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.2/peliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="catalogoPeliculas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pelicula" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pelicula">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="duracion" type="xs:positiveInteger"/>
        <xs:element name="genero" type="xs:string"/>
        <xs:element ref="actores"/>
        <xs:element ref="fecha"/>
        <xs:element name="director" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="formato" type="xs:string"/>
        <xs:element name="trailer" type="xs:string" minOccurs="0"/>
        <xs:element name="cartel" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="fecha">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="\d{4}|"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="actores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="actor" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  

</xs:schema>

=== chelunike/Clase2111DAWM/LMGSI/Solucion Ejercicios/Tema 6/Ejercicio 6.2/peliculas.xml
<?xml version="1.0"?>
<catalogoPeliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="peliculas.xsd">
	<pelicula>
		<titulo>The Matrix</titulo>
		<duracion>136</duracion>
		<genero>Sci-Fi and Fantasy</genero>
		<actores>
			<actor>Keanu Reeves</actor>
			<actor>Laurence Fishburne</actor>
			<actor>Carrie Ann Moss</actor>
		</actores>
		<fecha>1999</fecha>
		<director>Wachowski Brothers</director>
		<director>Wachowski Brothers</director>
		<formato>DVD</formato>
		<trailer>matrix.avi</trailer>
	</pelicula>
	<pelicula>
		<titulo>Titanic</titulo>
		<duracion>194</duracion>
		<genero>Drama</genero>
		<actores>
			<actor>Leonardo DiCaprio</actor>
			<actor>Kate Winslet</actor>
		</actores>
		<fecha>1999</fecha>
		<formato>DVD</formato>
		<cartel>titanic.jpg</cartel>
	</pelicula>
	<pelicula>
		<titulo>The Sixth Sense</titulo>
		<duracion>106</duracion>
		<genero>Thriller</genero>
		<actores>
			<actor>Bruce Willis</actor>
			<actor>Haley Joel Osment</actor>
		</actores>
		<fecha/>
		<director>M. Night Shyamalan</director>
		<formato>HD720</formato>
		<trailer>sixthSense.avi</trailer>
		<cartel> sixthSense.jpg</cartel>
	</pelicula>
</catalogoPeliculas>
